In [9]:
import pandas as pd

In [10]:
titanic_df = pd.read_csv('C:\\dev\\python\\exam02_311\\titanic3.csv') # csv 파일이 있어야 함

dict = {
    'name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
    'Year' : [2011, 2016, 2015, 2015],
    'Gender' : ['Male','Female', 'Male', 'Male']
}

df = pd.DataFrame(dict)

In [11]:
titanic_df.head(3)

pclass  survived                            name     sex    age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.00      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.92      1   
2       1         0    Allison, Miss. Helen Loraine  female   2.00      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON

In [12]:
titanic_df.tail(3)

pclass  survived                       name   sex   age  sibsp  parch  \
1306       3         0  Zakarian, Mr. Mapriededer  male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin  male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo  male  29.0      0      0   

      ticket   fare cabin embarked boat   body home.dest  
1306    2656  7.225   NaN        C  NaN  304.0       NaN  
1307    2670  7.225   NaN        C  NaN    NaN       NaN  
1308  315082  7.875   NaN        S  NaN    NaN       NaN

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    4 non-null      object
 1   Year    4 non-null      int64 
 2   Gender  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [14]:
titanic_df.info() # info : dataframe내의 컬럼명, 데이터 타입, Null 건수, 데이터 건수 정보 표시

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [15]:
df.describe() # 데이터 값들의 평균, 표준편차, 4분위 분포도, 숫자형 컬럼들에 대한 정보 표기

Year
count     4.000000
mean   2014.250000
std       2.217356
min    2011.000000
25%    2014.000000
50%    2015.000000
75%    2015.250000
max    2016.000000

In [16]:
titanic_df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881138     0.498854     0.385027   
std       0.837836     0.486055    14.413493     1.041658     0.865560   
min       1.000000     0.000000     0.170000     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [17]:
value_counts = titanic_df['pclass'].value_counts() #특정 값의 개수를 가져오는 것 -> 이후 분포도에 도움이 됨
print(value_counts)

pclass
3    709
1    323
2    277
Name: count, dtype: int64


In [18]:
# dataframe to list 하는 방법
import numpy as np

In [29]:
array1 = np.zeros((8,8))

print(array1)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [33]:
titanic_df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881138     0.498854     0.385027   
std       0.837836     0.486055    14.413493     1.041658     0.865560   
min       1.000000     0.000000     0.170000     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [37]:
titanic_df['Alass'] = 'pclass' # 해당 명령어는 지정한 칼럼의 값을 통째로 바꿈, 수정할 정보가 없다면 새로운 칼럼을 만듦

In [38]:
titanic_df.describe()

survived          age        sibsp        parch         fare  \
count  1309.000000  1046.000000  1309.000000  1309.000000  1308.000000   
mean      0.381971    29.881138     0.498854     0.385027    33.295479   
std       0.486055    14.413493     1.041658     0.865560    51.758668   
min       0.000000     0.170000     0.000000     0.000000     0.000000   
25%       0.000000    21.000000     0.000000     0.000000     7.895800   
50%       0.000000    28.000000     0.000000     0.000000    14.454200   
75%       1.000000    39.000000     1.000000     0.000000    31.275000   
max       1.000000    80.000000     8.000000     9.000000   512.329200   

             body  
count  121.000000  
mean   160.809917  
std     97.696922  
min      1.000000  
25%     72.000000  
50%    155.000000  
75%    256.000000  
max    328.000000

In [39]:
titanic_df.head(3)

pclass  survived                            name     sex    age  sibsp  \
0  Aclass         1   Allen, Miss. Elisabeth Walton  female  29.00      0   
1  Aclass         1  Allison, Master. Hudson Trevor    male   0.92      1   
2  Aclass         0    Allison, Miss. Helen Loraine  female   2.00      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest   Alass  
0                     St Louis, MO  pclass  
1  Montreal, PQ / Chesterville, ON  pclass  
2  Montreal, PQ / Chesterville, ON  pclass

In [45]:
# dataFrame 삭제

titanic_drop_df = titanic_df.drop('Age_0', axis=1, inplace = False)
# axis = 0은 행에 대한 삭제, axis = 1은 열에 대한 삭제
# inplace는 False의 경우 기존 데이터를 유지하고 처리하는 데이터만 변경
# inplace가 True인 경우 기존 데이터를 포함하여 데이터를 변경되고 return이 없어서 반환받아서 사용할 수 없다.
titanic_df.head(3)

KeyError: "['Age_0'] not found in axis"

In [46]:
titanic_df.describe()

survived          age        sibsp        parch         fare  \
count  1309.000000  1046.000000  1309.000000  1309.000000  1308.000000   
mean      0.381971    29.881138     0.498854     0.385027    33.295479   
std       0.486055    14.413493     1.041658     0.865560    51.758668   
min       0.000000     0.170000     0.000000     0.000000     0.000000   
25%       0.000000    21.000000     0.000000     0.000000     7.895800   
50%       0.000000    28.000000     0.000000     0.000000    14.454200   
75%       1.000000    39.000000     1.000000     0.000000    31.275000   
max       1.000000    80.000000     8.000000     9.000000   512.329200   

             body  
count  121.000000  
mean   160.809917  
std     97.696922  
min      1.000000  
25%     72.000000  
50%    155.000000  
75%    256.000000  
max    328.000000

In [47]:
titanic_df = pd.read_csv('titanic3.csv')

In [48]:
titanic_df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881138     0.498854     0.385027   
std       0.837836     0.486055    14.413493     1.041658     0.865560   
min       1.000000     0.000000     0.170000     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [53]:
titanic_drop_df = titanic_df.drop('Age = 0', axis= 1, inplace=False)
titanic_drop_df.head(3)

KeyError: "['Age = 0'] not found in axis"

In [54]:
titanic_df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

In [56]:
titanic_df[['name', 'age']] # 선택한 칼럼만 띄워줌

name    age
0                       Allen, Miss. Elisabeth Walton  29.00
1                      Allison, Master. Hudson Trevor   0.92
2                        Allison, Miss. Helen Loraine   2.00
3                Allison, Mr. Hudson Joshua Creighton  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.00
...                                               ...    ...
1304                             Zabour, Miss. Hileni  14.50
1305                            Zabour, Miss. Thamine    NaN
1306                        Zakarian, Mr. Mapriededer  26.50
1307                              Zakarian, Mr. Ortin  27.00
1308                               Zimmerman, Mr. Leo  29.00

[1309 rows x 2 columns]

In [57]:
titanic_df[titanic_df['pclass'] == 3]

pclass  survived                              name     sex   age  sibsp  \
600        3         0               Abbing, Mr. Anthony    male  42.0      0   
601        3         0     Abbott, Master. Eugene Joseph    male  13.0      0   
602        3         0       Abbott, Mr. Rossmore Edward    male  16.0      1   
603        3         1  Abbott, Mrs. Stanton (Rosa Hunt)  female  35.0      1   
604        3         1       Abelseth, Miss. Karen Marie  female  16.0      0   
...      ...       ...                               ...     ...   ...    ...   
1304       3         0              Zabour, Miss. Hileni  female  14.5      1   
1305       3         0             Zabour, Miss. Thamine  female   NaN      1   
1306       3         0         Zakarian, Mr. Mapriededer    male  26.5      0   
1307       3         0               Zakarian, Mr. Ortin    male  27.0      0   
1308       3         0                Zimmerman, Mr. Leo    male  29.0      0   

      parch     ticket     fare cabin embarked boat   body  \
600       0  C.A. 5547   7.5500   NaN        S  NaN    NaN   
601       2  C.A. 2673  20.2500   NaN        S  NaN    NaN   
602       1  C.A. 2673  20.2500   NaN        S  NaN  190.0   
603       1  C.A. 2673  20.2500   NaN        S    A    NaN   
604       0     348125   7.6500   NaN        S   16    NaN   
...     ...        ...      ...   ...      ...  ...    ...   
1304      0       2665  14.4542   NaN        C  NaN  328.0   
1305      0       2665  14.4542   NaN        C  NaN    NaN   
1306      0       2656   7.2250   NaN        C  NaN  304.0   
1307      0       2670   7.2250   NaN        C  NaN    NaN   
1308      0     315082   7.8750   NaN        S  NaN    NaN   

                   home.dest  
600                      NaN  
601      East Providence, RI  
602      East Providence, RI  
603      East Providence, RI  
604   Norway Los Angeles, CA  
...                      ...  
1304                     NaN  
1305                     NaN  
1306                     NaN  
1307                     NaN  
1308                     NaN  

[709 rows x 14 columns]

In [60]:
titanic_df[titanic_df['age'] > 1] # [] 내부 조건에 맞는 리스트만 띄워줌

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
5          1         1                              Anderson, Mr. Harry   
...      ...       ...                                              ...   
1301       3         0                             Youseff, Mr. Gerious   
1304       3         0                             Zabour, Miss. Hileni   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex   age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0      0      0   24160  211.3375       B5        S    2   
2     female   2.0      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0      1      2  113781  151.5500  C22 C26        S  NaN   
5       male  48.0      0      0   19952   26.5500      E12        S    3   
...      ...   ...    ...    ...     ...       ...      ...      ...  ...   
1301    male  45.5      0      0    2628    7.2250      NaN        C  NaN   
1304  female  14.5      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
5       NaN                     New York, NY  
...     ...                              ...  
1301  312.0                              NaN  
1304  328.0                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1024 rows x 14 columns]

In [61]:
titanic_df[titanic_df['age'] > 1][['name','age']] # 리스트처럼 섞기 가능

name   age
0                       Allen, Miss. Elisabeth Walton  29.0
2                        Allison, Miss. Helen Loraine   2.0
3                Allison, Mr. Hudson Joshua Creighton  30.0
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0
5                                 Anderson, Mr. Harry  48.0
...                                               ...   ...
1301                             Youseff, Mr. Gerious  45.5
1304                             Zabour, Miss. Hileni  14.5
1306                        Zakarian, Mr. Mapriededer  26.5
1307                              Zakarian, Mr. Ortin  27.0
1308                               Zimmerman, Mr. Leo  29.0

[1024 rows x 2 columns]

In [67]:
titanic_df.iloc[1, 2] # 행렬의 n,m을 따라가서 어떤 값이 들어있는지 확인

'Allison, Master. Hudson Trevor'

In [65]:
titanic_df.loc[1, 'name'] #행렬의 칼럼 제목을 따라가서 어떤 값이 들어있는지 확인

'Allison, Master. Hudson Trevor'

In [66]:
titanic_df.head(3) #위의 함수는 행, 렬에 지정된 칼럼을 입력하여 값을 도출

pclass  survived                            name     sex    age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.00      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.92      1   
2       1         0    Allison, Miss. Helen Loraine  female   2.00      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON

In [68]:
titanic_df.sort_values(by=['survived'])

pclass  survived                                             name  \
16         1         0                         Baxter, Mr. Quigg Edmond   
19         1         0                             Beattie, Mr. Thomson   
7          1         0                           Andrews, Mr. Thomas Jr   
9          1         0                          Artagaveytia, Mr. Ramon   
10         1         0                           Astor, Col. John Jacob   
...      ...       ...                                              ...   
1          1         1                   Allison, Master. Hudson Trevor   
5          1         1                              Anderson, Mr. Harry   
1286       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
0          1         1                    Allen, Miss. Elisabeth Walton   
1290       3         1                 Wilkes, Mrs. James (Ellen Needs)   

         sex    age  sibsp  parch    ticket      fare    cabin embarked boat  \
16      male  24.00      0      1  PC 17558  247.5208  B58 B60        C  NaN   
19      male  36.00      0      0     13050   75.2417       C6        C    A   
7       male  39.00      0      0    112050    0.0000      A36        S  NaN   
9       male  71.00      0      0  PC 17609   49.5042      NaN        C  NaN   
10      male  47.00      1      0  PC 17757  227.5250  C62 C64        C  NaN   
...      ...    ...    ...    ...       ...       ...      ...      ...  ...   
1       male   0.92      1      2    113781  151.5500  C22 C26        S   11   
5       male  48.00      0      0     19952   26.5500      E12        S    3   
1286  female  38.00      0      0      2688    7.2292      NaN        C    C   
0     female  29.00      0      0     24160  211.3375       B5        S    2   
1290  female  47.00      1      0    363272    7.0000      NaN        S  NaN   

       body                        home.dest  
16      NaN                     Montreal, PQ  
19      NaN                     Winnipeg, MN  
7       NaN                      Belfast, NI  
9      22.0              Montevideo, Uruguay  
10    124.0                     New York, NY  
...     ...                              ...  
1       NaN  Montreal, PQ / Chesterville, ON  
5       NaN                     New York, NY  
1286    NaN                              NaN  
0       NaN                     St Louis, MO  
1290    NaN                              NaN  

[1309 rows x 14 columns]

In [69]:
titanic_df.count()

pclass       1309
survived     1309
name         1309
sex          1309
age          1046
sibsp        1309
parch        1309
ticket       1309
fare         1308
cabin         295
embarked     1307
boat          486
body          121
home.dest     745
dtype: int64

In [70]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [74]:
titanic_df[['age']].mean()

age    29.881138
dtype: float64

In [75]:
titanic_df['age'].mean()

np.float64(29.881137667304014)

In [76]:
titanic_groupby = titanic_df.groupby(by = 'pclass')

In [78]:
titanic_groupby.count()

survived  name  sex  age  sibsp  parch  ticket  fare  cabin  embarked  \
pclass                                                                          
1            323   323  323  284    323    323     323   323    256       321   
2            277   277  277  261    277    277     277   277     23       277   
3            709   709  709  501    709    709     709   708     16       709   

        boat  body  home.dest  
pclass                         
1        201    35        289  
2        112    31        261  
3        173    55        195

In [79]:
titanic_df.groupby('pclass')['age'].agg([max,min])

C:\Users\USER\AppData\Local\Temp\ipykernel_20940\1025027121.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  titanic_df.groupby('pclass')['age'].agg([max,min])
C:\Users\USER\AppData\Local\Temp\ipykernel_20940\1025027121.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  titanic_df.groupby('pclass')['age'].agg([max,min])


max   min
pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.17

In [81]:
agg_format = {'age':'max', 'age':'mean', 'fare':'mean'}
titanic_df.groupby('pclass').agg(agg_format)

age       fare
pclass                      
1       39.159930  87.508992
2       29.506705  21.179196
3       24.816367  13.302889