In [2]:
import numpy as np

list1 = [1,2,3]
array1 = np.array(list1) 
array2 = np.array([[1,2,3],
                   [2,3,4],])
array3 = np.array([[1,2,3]])

print("array1 array 형태:", array1.shape) #(3, )
print("array2 array 형태:", array2.shape) #(2, 3)
print("array3 array 형태:", array3.shape) #(1, 2)

array1 array 형태: (3,)
array2 array 형태: (2, 3)
array3 array 형태: (1, 3)


In [25]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
array_float2 = array_int.astype(np.float64) #메모리 할당 변화
print(array_int)
print(array_float)
print(array_float2)

[1 2 3]
[1. 2. 3.]
[1. 2. 3.]


In [24]:
array1 = np.arange(10)
print(array1)

#(2, 5) shape로 변경
array2 = array1.reshape(2, 5)
print(array2)

#(5, 2) shae로 변경
array3 = array1.reshape(5, -1) # 위에서 array1의 데이터 갯수는 10개로 지정되었고 이를 reshape하는 것이므로 데이터 갯수는 같아야함
                               # 따라서 앞에 5를 넣고 뒤에 -1을 집어넣어도 -1 대신에 데이터 갯수를 맞추기 위한 2가 자동으로 들어간다.
print(array3)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array = np.arange(start=1, stop=10)
array[1:3] #인덱스 1부터 3이전 데이터 처리
array[3:] #인덱스 3부터 모든 데이터 처리
array[:2] #인덱스 2 이전까지 데이터 처리
array[:] #모든 데이터 처리
array[:-1] #마지막 데이터 제외

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
array = np.arange(start=1, stop = 10)
print(array[[1, 4, 7]]) #팬시 인덱싱 = 리스트로 인덱스를 주어 원하는 인덱스를 가져올 수 있다.
print(array[array > 5]) #boolean 인덱싱 = 해당 조건을 만족하는 값만 가져온다.

[2 5 8]
[6 7 8 9]


In [23]:
# 정렬

array1d = np.array([78, 95, 84, 98, 88])
sort_array1_asc = np.sort(array1d) # 오름차순 정렬
sort_array1_desc = np.sort(array1d)[::-1] #내림차순 정렬 -> 뒤에 슬라이싱의 -1텀을 이용하여서 정렬
sort_array1d_index = np.argsort(array1d) #argsort = 데이터를 정렬했을 때, 인덱스를 리턴

print(sort_array1_asc)
print(sort_array1_desc)
print(sort_array1d_index,"\n")

array2d = np.array([[7, 8, 9], [4, 5, 6], [1, 2, 3]])
sort_array2d_axis0 = np.sort(array2d, axis=0) # 2차원 정렬, 축방향 = 0 -> 행을 기준으로 index = 0이 제일 위에 깔리게 array[행][렬], array[y][x]

print(array2d)
print(sort_array2d_axis0)

[78 84 88 95 98]
[98 95 88 84 78]
[0 2 4 1 3] 

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# 데이터 생성

print(np.array(10)) # 특정 범위의 데이터를 포함한 ndarray를 생성하는 방법
print(np.ones((3,2))) # 모든 값이 1인 nparray를 만들어 준다. axis 값을 받아 원하는 shape의 데이터를 생성
print(np.zeros((3,2), dtype='int32')) # 모든 값이 0인 값을 만들어 준다.

10
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0 0]
 [0 0]
 [0 0]]


In [16]:
# 행렬 내적

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [28]:
# 전치행렬 -> A(i, j)를 A(j, i)로 변경한 행렬

A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
